// docs/.vitepress/components/BackToTop.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'

const visible = ref(false)

const handleScroll = () => {
  visible.value = window.scrollY > 300
}

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  })
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <transition name="fade">
    <button
      v-if="visible"
      class="back-to-top"
      aria-label="Back to Top"
      @click="scrollToTop"
    >
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <path d="M18 15l-6-6-6 6"/>
      </svg>
    </button>
  </transition>
</template>

<style scoped>
.back-to-top {
  position: fixed;
  bottom: 24px;
  right: 24px;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.7);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 999;
  transition: all 0.3s cubic-bezier(0.25, 1, 0.5, 1);
  box-shadow: 0 8px 20px rgba(0,0,0,0.2);
}

.back-to-top:hover {
  transform: translateY(-4px);
  background: rgba(0, 0, 0, 0.9);
  box-shadow: 0 12px 24px rgba(0,0,0,0.3);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease, transform 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(20px);
}

@media (prefers-color-scheme: dark) {
  .back-to-top {
    background: rgba(255, 255, 255, 0.2);
    color: white;
  }
  .back-to-top:hover {
    background: rgba(255, 255, 255, 0.3);
  }
}
</style>

// components/ui/BackToTop.tsx
"use client"

import React, { useState, useEffect } from 'react'
import { ArrowUp } from 'lucide-react'

const BackToTop: React.FC = () => {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      // 滾動超過 400px 就顯示，比百分比更直覺且一致
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop
      setVisible(scrollTop > 400)
    }

    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <button
      onClick={scrollToTop}
      className={`fixed bottom-8 right-6 md:right-10 w-12 h-12 md:w-14 md:h-14 rounded-full bg-apple-blue text-white shadow-2xl shadow-apple-blue/30 flex items-center justify-center z-150 transition-all duration-500 transform ${
        visible 
          ? 'translate-y-0 opacity-100 scale-100' 
          : 'translate-y-16 opacity-0 scale-75 pointer-events-none'
      } hover:scale-110 active:scale-95 group`}
      aria-label="Back to Top"
    >
      {/* 呼吸波紋動畫 */}
      <div className="absolute inset-0 rounded-full bg-apple-blue/40 animate-ping opacity-25 group-hover:hidden" />
      
      {/* 內圈裝飾 */}
      <div className="absolute inset-1 rounded-full border border-white/20 pointer-events-none" />
      
      <ArrowUp className="w-5 h-5 md:w-6 md:h-6 group-hover:-translate-y-1.5 transition-transform duration-300" />
    </button>
  )
}

export default BackToTop
