// docs/.vitepress/components/ui/EmptyState.vue
<script setup lang="ts">
import { computed } from "vue";
import { useData } from "vitepress";

defineProps<{
  icon?: string;
  title?: string;
  description?: string;
  actionText?: string;
}>();

const { lang } = useData();
const t = computed(() => {
  return lang.value === "zh-TW"
    ? {
        title: "找不到相關結果",
        desc: "請嘗試使用不同的關鍵字，或者檢查拼字是否正確。",
      }
    : {
        title: "No results found",
        desc: "Please try using different keywords or check your spelling.",
      };
});

defineEmits<{ (e: "clear"): void }>();
</script>

<template>
  <div class="empty-results">
    <div class="empty-icon">{{ icon || "🔍" }}</div>
    <h3>{{ title || t.title }}</h3>
    <p>{{ description || t.desc }}</p>
    <button v-if="actionText" @click="$emit('clear')" class="clear-btn">
      {{ actionText }}
    </button>
  </div>
</template>

<style scoped>
.empty-results {
  text-align: center;
  padding: 80px 24px;
  background: var(--vp-c-bg-alt);
  border-radius: 24px;
  border: 1px dashed var(--vp-c-divider);
  margin-top: 40px;
}

.empty-icon {
  font-size: 48px;
  margin-bottom: 20px;
}

.empty-results h3 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 12px;
}

.empty-results p {
  color: var(--vp-c-text-3);
  margin-bottom: 24px;
}

.clear-btn {
  padding: 10px 24px;
  background: var(--vp-c-brand-1);
  color: white;
  border-radius: 99px;
  border: none;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.clear-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 113, 227, 0.3);
}
</style>

// components/ui/EmptyState.tsx
import React from 'react'
import { useRouter } from 'next/router'
import { SearchX } from 'lucide-react'

interface EmptyStateProps {
  icon?: string
  title?: string
  description?: string
  actionText?: string
  onClear?: () => void
}

const EmptyState: React.FC<EmptyStateProps> = ({
  icon = '🔍',
  title,
  description,
  actionText,
  onClear
}) => {
  const { locale } = useRouter()
  
  const t = {
    title: locale === 'en' ? 'No results found' : '找不到相關結果',
    desc: locale === 'en' 
      ? 'Please try using different keywords or check your spelling.' 
      : '請嘗試使用不同的關鍵字，或者檢查拼字是否正確。'
  }

  return (
    <div className="text-center py-24 px-6 bg-zinc-50/50 dark:bg-white/[0.02] rounded-[32px] border border-zinc-200/50 dark:border-white/10 mt-10 transition-all">
      <div className="flex justify-center mb-6">
        <div className="w-20 h-20 bg-blue-50 dark:bg-blue-500/10 rounded-[24px] flex items-center justify-center text-blue-600 dark:text-blue-400">
          <SearchX className="w-10 h-10" />
        </div>
      </div>
      <h3 className="text-2xl font-black text-zinc-900 dark:text-white mb-3 tracking-tight">{title || t.title}</h3>
      <p className="text-zinc-500 dark:text-zinc-400 mb-8 max-w-sm mx-auto leading-relaxed font-medium">{description || t.desc}</p>
      {actionText && (
        <button 
          onClick={onClear}
          className="px-8 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-2xl font-bold transition-all active:scale-95 shadow-xl shadow-blue-500/20"
        >
          {actionText}
        </button>
      )}
    </div>
  )
}

export default EmptyState
