// docs/.vitepress/theme/components/SecurityGuard.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { useRouter, useData } from 'vitepress';

const { site } = useData();
const router = useRouter();

const handleContextMenu = (e: MouseEvent) => {
  e.preventDefault();
  console.warn('⚠️ 本站原創內容，未經授權禁止複製或側錄。');
};

const handleKeyDown = (e: KeyboardEvent) => {
  // 禁止 Ctrl+S, Ctrl+U, Ctrl+P, F12, Ctrl+Shift+I, Alt+Cmd+I
  const isForbidden =
    (e.keyCode === 123) || // F12
    ((e.ctrlKey || e.metaKey) && e.keyCode === 85) || // Ctrl+U
    ((e.ctrlKey || e.metaKey) && e.keyCode === 83) || // Ctrl+S
    ((e.ctrlKey || e.metaKey) && e.keyCode === 80) || // Ctrl+P
    ((e.ctrlKey || e.metaKey) && e.shiftKey && e.keyCode === 73) || // Ctrl+Shift+I
    ((e.ctrlKey || e.metaKey) && e.shiftKey && e.keyCode === 67) || // Ctrl+Shift+C
    (e.metaKey && e.altKey && e.keyCode === 73); // Mac Opt+Cmd+I

  if (isForbidden) {
    e.preventDefault();
    console.error('🛡️ 系統已攔截受限操作 (Security Intercepted)');
  }
};

const handleCopy = (e: ClipboardEvent) => {
  e.preventDefault();
  const msg = '🔒 本站內容受技術保護，禁止複製或側錄。';
  if (e.clipboardData) {
    e.clipboardData.setData('text/plain', msg);
  }
  console.error('🛡️ 複製操作已被攔截');
};

// 基礎防護：攔截右鍵、快捷鍵與複製
onMounted(() => {
  // Automatic Language Detection
  if (typeof window !== 'undefined') {
    const userLang = navigator.language || (navigator as any).userLanguage || '';
    const isChinese = userLang.toLowerCase().startsWith('zh');
    const currentPath = window.location.pathname;
    const isEnPath = currentPath.includes('/en/');
    const hasRedirected = sessionStorage.getItem('lang-redirect-checked');

    // If browser is not Chinese, and we are NOT on an English page, and haven't checked yet
    if (!isChinese && !isEnPath && !hasRedirected) {
      sessionStorage.setItem('lang-redirect-checked', 'true');

      const base = site.value?.base || '/';
      const cleanPath = currentPath.startsWith(base)
        ? currentPath.slice(base.length)
        : currentPath;

      const target = base + 'en/' + (cleanPath.startsWith('/') ? cleanPath.slice(1) : cleanPath);
      router.go(target);
    }
  }

  document.addEventListener('contextmenu', handleContextMenu);
  document.addEventListener('keydown', handleKeyDown);
  document.addEventListener('copy', handleCopy);

  // 強制 CSS 禁止選擇 (如果需要更嚴格)
  document.body.style.userSelect = 'none';
  document.body.style.webkitUserSelect = 'none';

  console.log('%c🛡️ MDM Support Shield Active', 'color: #ff3b30; font-weight: bold;');
});

onUnmounted(() => {
  document.removeEventListener('contextmenu', handleContextMenu);
  document.removeEventListener('keydown', handleKeyDown);
  document.removeEventListener('copy', handleCopy);
  document.body.style.userSelect = 'auto';
  document.body.style.webkitUserSelect = 'auto';
});
</script>

<template>
  <div style="display: none;" aria-hidden="true"></div>
</template>

// components/features/SecurityGuard.tsx
"use client"

import React, { useEffect, useState } from 'react'
// ✅ 在 App Router 下，必須改用 next/navigation
import { useRouter } from 'next/navigation'
import { useLanguage } from '@/hooks/useLanguage'

const SecurityGuard: React.FC = () => {
  const router = useRouter()
  const { language, setLanguage } = useLanguage()
  const [isMounted, setIsMounted] = useState(false)

  // 1. 處理掛載狀態，防止 Hydration 錯誤
  useEffect(() => {
    setIsMounted(true)
  }, [])

  // 2. 語系自動導向 (僅限 Session 首次啟動)
  useEffect(() => {
    if (typeof window === "undefined" || !isMounted) return

    const checkLanguageRedirect = () => {
      const userLang = navigator.language || ""
      const isChinese = userLang.toLowerCase().startsWith("zh")
      const hasRedirected = sessionStorage.getItem("lang-redirect-checked")

      if (!isChinese && language === 'zh-TW' && !hasRedirected) {
        sessionStorage.setItem("lang-redirect-checked", "true")
        setLanguage('en')
        console.log("🌐 Auto-switched language to English based on browser settings.")
      }
    }

    checkLanguageRedirect()
  }, [language, setLanguage, isMounted])

  // 3. 安全事件監聽 (右鍵、快捷鍵、複製、拖曳)
  useEffect(() => {
    if (!isMounted) return

    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault()
    }

    const handleKeyDown = (e: KeyboardEvent) => {
      // ✅ 使用 e.key 取代 e.keyCode (更好的跨平台支援)
      const ctrlOrMeta = e.ctrlKey || e.metaKey
      
      const isForbidden =
        e.key === 'F12' ||
        (ctrlOrMeta && e.key === 'u') || // 查看原始碼
        (ctrlOrMeta && e.key === 's') || // 儲存網頁
        (ctrlOrMeta && e.key === 'p') || // 列印
        (ctrlOrMeta && e.shiftKey && (e.key === 'I' || e.key === 'C' || e.key === 'J')) || // 開發者工具
        (e.metaKey && e.altKey && e.key === 'i') // Mac DevTools

      if (isForbidden) {
        e.preventDefault()
        e.stopPropagation()
      }
    }

    const handleCopy = (e: ClipboardEvent) => {
      const msg = "🔒 本站內容受技術保護，禁止複製或側錄。\n\n如需引用，請聯繫：hsuan@superinfo.com.tw"
      e.clipboardData?.setData("text/plain", msg)
      e.preventDefault()
    }

    const handleDragStart = (e: DragEvent) => {
      e.preventDefault()
    }

    document.addEventListener("contextmenu", handleContextMenu)
    document.addEventListener("keydown", handleKeyDown)
    document.addEventListener("copy", handleCopy)
    document.addEventListener("dragstart", handleDragStart)

    return () => {
      document.removeEventListener("contextmenu", handleContextMenu)
      document.removeEventListener("keydown", handleKeyDown)
      document.removeEventListener("copy", handleCopy)
      document.removeEventListener("dragstart", handleDragStart)
    }
  }, [isMounted])

  // 4. 開發者工具與自動化偵測
  useEffect(() => {
    if (process.env.NODE_ENV === 'development' || !isMounted) return

    let devtoolsOpen = false
    const detectDevTools = () => {
      const threshold = 160
      const isDevToolsOpen = 
        window.outerWidth - window.innerWidth > threshold || 
        window.outerHeight - window.innerHeight > threshold
      
      if (isDevToolsOpen) {
        if (!devtoolsOpen) {
          devtoolsOpen = true
          console.clear()
          console.log("%c⚠️ 警告 Warning", "color: red; font-size: 40px; font-weight: bold;")
          console.log("%c請勿在此執行任何指令！", "font-size: 16px;")
        }
      } else {
        devtoolsOpen = false
      }
    }

    const intervalId = setInterval(detectDevTools, 2000)
    return () => clearInterval(intervalId)
  }, [isMounted])

  // 5. 注入全局 CSS (禁止選擇與列印保護)
  useEffect(() => {
    if (!isMounted) return

    const styleId = 'security-guard-styles'
    if (!document.getElementById(styleId)) {
      const style = document.createElement('style')
      style.id = styleId
      style.innerHTML = `
        body {
          -webkit-user-select: none !important;
          user-select: none !important;
        }
        input, textarea, [contenteditable="true"] {
          -webkit-user-select: text !important;
          user-select: text !important;
        }
        @media print {
          body { display: none !important; }
        }
      `
      document.head.appendChild(style)
    }
  }, [isMounted])

  if (!isMounted) return null

  return null
}

export default SecurityGuard
